import type { Metadata } from "next";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header id="header"></header>
        <main id="main">{children}</main>
        <footer id="footer"></footer>
      </body>
    </html>
  );
}
