import type { Metadata } from "next";

import TopNavBar from "@/components/top_nav_bar/top_nav_bar";
import StoreProvider from "../store/store_provider";

import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body>
          <TopNavBar />
          <main id="main">{children}</main>
          <footer id="footer"></footer>
        </body>
      </StoreProvider>
    </html>
  );
}
